### ISSUE TITLE
徽章建议

### ISSUE THREAD

**Issue by YingLing3** [rainerosion/skyBadge#1]
1.自己魔改了下，新增了一个修改使用次数的选项，假设用户不小心使用了徽章本体导致链接失效，js无须重新录入，直接修改链接的16进制次数。
2.建议将徽章数据存储到sd卡内而不是auto内部，这样用户可以带着数据文件直接去其他手机使用，无须再次录入。

**Comment by rainerosion** [comment]
1. 方便的话可以提个PR贡献下你修改的代码，目前比较忙，没太多时间去改。
2. 存储方式其实如果添加一个导入导出功能是不是就可以解决更换设备的问题了，依旧沿用auto来存储数据

**Comment by rainerosion** [comment]
更新次数功能已更新到最新代码，导入导出功能有空了下个版本做。
